# -*- coding: utf-8 -*-
"""3rd attemt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17kLdLBosqzWq-jlf6XjEqoNMwNjwpX9i
"""

# full_fixed_timeseries_with_shap.py
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'  # reduce TF logging

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import (
    LSTM, Dense, Dropout, Input, LayerNormalization,
    MultiHeadAttention, Layer
)
import shap
import random

# Reproducibility
SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)
random.seed(SEED)

# -------------------------------------------------------------
# 1. Generate Synthetic Time-Series Data
# -------------------------------------------------------------
time = np.arange(0, 1000)

series = (
    10 + 0.02 * time +                            # upward trend
    5 * np.sin(0.02 * time) +                     # seasonality
    np.random.normal(scale=1.5, size=len(time))   # noise
)

exogenous = np.random.normal(0, 1, len(time))     # external regressor

df = pd.DataFrame({
    "value": series,
    "exo": exogenous
})

# -------------------------------------------------------------
# 2. Train-Test Split
# -------------------------------------------------------------
train_size = 800
train, test = df.iloc[:train_size], df.iloc[train_size:]

# -------------------------------------------------------------
# 3. Scaling
# -------------------------------------------------------------
scaler = MinMaxScaler()
train_scaled = scaler.fit_transform(train)   # shape: (800,2)
test_scaled = scaler.transform(test)         # shape: (200,2)

# -------------------------------------------------------------
# 4. Create Windowed Dataset
# -------------------------------------------------------------
def create_dataset(data, window=30, horizon=1):
    X, y = [], []
    for i in range(len(data) - window - horizon + 1):
        X.append(data[i:i+window])
        y.append(data[i+window+horizon-1][0])   # predict the 'value' column
    return np.array(X), np.array(y)

WINDOW = 30
HORIZON = 1

X_train, y_train = create_dataset(train_scaled, WINDOW, HORIZON)
X_test, y_test = create_dataset(test_scaled, WINDOW, HORIZON)

print("X_train shape:", X_train.shape)
print("X_test  shape:", X_test.shape)

# -------------------------------------------------------------
# 5. Build LSTM Model
# -------------------------------------------------------------
def build_lstm(window=WINDOW):
    model = Sequential([
        LSTM(64, return_sequences=True, input_shape=(window, 2)),
        Dropout(0.2),
        LSTM(32),
        Dense(16, activation='relu'),
        Dense(1)
    ])
    model.compile(optimizer='adam', loss='mse')
    return model

lstm_model = build_lstm()
lstm_model.summary()

# -------------------------------------------------------------
# 6. Build Transformer Model
# -------------------------------------------------------------
class TransformerBlock(tf.keras.layers.Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, rate=0.1):
        super().__init__()
        self.att = MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim)
        self.ffn = Sequential([
            Dense(ff_dim, activation="relu"),
            Dense(embed_dim)
        ])
        self.layernorm1 = LayerNormalization()
        self.layernorm2 = LayerNormalization()
        self.dropout1 = Dropout(rate)
        self.dropout2 = Dropout(rate)

    def call(self, inputs, training=False):
        # Self-attention
        attn_output = self.att(inputs, inputs)
        attn_output = self.dropout1(attn_output, training=training)
        out1 = self.layernorm1(inputs + attn_output)

        # Feed-forward
        ffn_output = self.ffn(out1)
        ffn_output = self.dropout2(ffn_output, training=training)
        return self.layernorm2(out1 + ffn_output)

# Custom layer to wrap tf.reduce_mean
class ReduceMeanLayer(Layer):
    def call(self, inputs):
        return tf.reduce_mean(inputs, axis=1)

def build_transformer(window=WINDOW):
    inputs = Input(shape=(window, 2))
    embed_dim = 32
    num_heads = 2
    ff_dim = 64

    # Project the input features to embed_dim
    x = Dense(embed_dim, activation='relu')(inputs)
    x = TransformerBlock(embed_dim, num_heads, ff_dim)(x)
    x = ReduceMeanLayer()(x)  # collapse time axis
    x = Dense(32, activation='relu')(x)
    outputs = Dense(1)(x)
    model = Model(inputs, outputs)
    model.compile(optimizer='adam', loss='mse')
    return model

transformer_model = build_transformer()
transformer_model.summary()

# -------------------------------------------------------------
# 7. Train Models
# -------------------------------------------------------------
EPOCHS = 10
BATCH = 32

history_lstm = lstm_model.fit(X_train, y_train, epochs=EPOCHS, batch_size=BATCH, verbose=1)
history_tr = transformer_model.fit(X_train, y_train, epochs=EPOCHS, batch_size=BATCH, verbose=1)

# -------------------------------------------------------------
# 8. Predictions
# -------------------------------------------------------------
lstm_pred = lstm_model.predict(X_test)
transformer_pred = transformer_model.predict(X_test)

# Inverse scaling: scaler expects 2 columns (value, exo), so concat zeros for exo
def inv_scale_single_col(col):
    arr = np.hstack([col.reshape(-1,1), np.zeros((len(col),1))])
    return scaler.inverse_transform(arr)[:,0]

true_values = inv_scale_single_col(y_test)
lstm_pred = inv_scale_single_col(lstm_pred.ravel())
transformer_pred = inv_scale_single_col(transformer_pred.ravel())

# -------------------------------------------------------------
# 9. Evaluation Metrics
# -------------------------------------------------------------
def evaluate(true, pred, name):
    mae = mean_absolute_error(true, pred)
    rmse = np.sqrt(mean_squared_error(true, pred))
    # avoid divide-by-zero in MAPE
    safe_true = np.where(true == 0, 1e-8, true)
    mape = np.mean(np.abs((true - pred) / safe_true)) * 100

    print(f"\n{name} Evaluation:")
    print(f"MAE : {mae:.4f}")
    print(f"RMSE: {rmse:.4f}")
    print(f"MAPE: {mape:.2f}%")

evaluate(true_values, lstm_pred, "LSTM")
evaluate(true_values, transformer_pred, "Transformer")

# -------------------------------------------------------------
# 10. Plots: Predictions vs True
# -------------------------------------------------------------
plt.figure(figsize=(12,5))
plt.plot(true_values, label="True")
plt.plot(lstm_pred, label="LSTM")
plt.plot(transformer_pred, label="Transformer")
plt.legend()
plt.title("Model Forecast vs True Values")
plt.xlabel("Test index")
plt.ylabel("Value")
plt.show()

# -------------------------------------------------------------
# 11. SHAP Explainability (LSTM) - KernelExplainer (TF2 Compatible)
# -------------------------------------------------------------
# NOTE: KernelExplainer is model-agnostic but can be slow. We use a small background sample.
shap.initjs()

# Flatten time-series windows for KernelExplainer
X_train_flat = X_train.reshape((X_train.shape[0], -1))
X_test_flat = X_test.reshape((X_test.shape[0], -1))

# Pick a small background set (50 samples or fewer if not available)
bg_size = min(50, X_train_flat.shape[0])
bg_idx = np.random.choice(X_train_flat.shape[0], bg_size, replace=False)
background = X_train_flat[bg_idx]

# Define a prediction function that accepts flattened input
def predict_from_flat(x_flat):
    # x_flat shape: (n_samples, window*2)
    x_reshaped = x_flat.reshape((-1, WINDOW, 2))
    preds = lstm_model.predict(x_reshaped, verbose=0)
    return preds.ravel()

# Create KernelExplainer
explainer = shap.KernelExplainer(predict_from_flat, background)

# Explain first N test samples (keep N small)
N_EXPLAIN = min(20, X_test_flat.shape[0])
# nsamples controls speed/accuracy of approximation
shap_values = explainer.shap_values(X_test_flat[:N_EXPLAIN], nsamples=100)

# Build readable feature names: order matches flattening [t0_val, t0_exo, t1_val, t1_exo, ...]
feature_names = []
for t in range(WINDOW):
    # label with relative lag (t from oldest to newest)
    lag = WINDOW - t
    feature_names.append(f"value_t-{lag}")
    feature_names.append(f"exo_t-{lag}")

# Plot SHAP summary (be aware KernelExplainer returns a list; for single-output model shap_values is array)
if isinstance(shap_values, list) and len(shap_values) == 1:
    shap_v = shap_values[0]
else:
    shap_v = np.array(shap_values)

# summary_plot expects shape (samples, features)
shap.summary_plot(shap_v, X_test_flat[:N_EXPLAIN], feature_names=feature_names)